/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Arrays;
import java.util.Objects;

public class App {

    public static void main(String[] args) {
        int i;
        String forma = " ";
        int dimensoes = 0;
        int alturaRetangulo = 0;

        for (i = 0; i < args.length; i++) { // for para verificar todos os argumentos
            if (Objects.equals(args[i], args[0])) { // conferir arg[0] para ver se é uma forma
                if ("triangulo".equals(args[0]) || "losangulo".equals(args[0]) || "retangulo".equals(args[0])) {
                    forma = args[0];
                    if (forma.equals("retangulo")) {
                        if (isNumeric(args[2])) { // conferir a arg[2] para ve se é a dimensão do retangulo
                             alturaRetangulo = Integer.parseInt(args[2]);
                        } else {
                            dimensaoInvalida();
                            break;
                        }
                    }
                }
                else {
                    dimensaoInvalida();
                    break;
                }
            }
            if (Objects.equals(args[i], args[1])) { // conferir arg[1] para ve se é uma dimensão
                if (isNumeric(args[1])) {
                     dimensoes = Integer.parseInt(args[1]);
                    if (Objects.equals(args[0], "losangulo") && (dimensoes % 2) == 0) {
                        System.out.println("É obrigatório que as dimensões do losangulo sejam ímpares");
                    }
                }
                else {
                    dimensaoInvalida();
                }
            }
        }
        switch (forma){ // switch case para cada tipo de forma
            case "triangulo":
                triangulo(dimensoes);
                break;
            case "losangulo":
                losangulo(dimensoes);
                break;
            case "retangulo":
                retangulo(dimensoes, alturaRetangulo);
                break;
            default:
                dimensaoInvalida();
        }
    }

    public static boolean isNumeric(String str) {
        return str.matches("-?\\d+(\\.\\d+)?");  // Verifica inteiros e decimais
    }

    public static void dimensaoInvalida(){
        System.out.println("Digite novamente conforme a ordem: forma/dimensões"); // mensagem de dimensões inválidas
    }

    public static void triangulo(int dimensao){
        char[] triangulo = new char[dimensao];

        for (int i = dimensao; i > 0; i--){ // for responsável por adicionar o * de forma decremental
            triangulo[i - 1] = '*';
            for (int j = 0; j < dimensao; j++){ // for responsável por mostrar na tela os triângulos
                if (triangulo[j] != 0){ // verifica se a posição está vazia ou não
                    System.out.print(triangulo[j]);
                }
                else {
                    System.out.print(" ");
                }
            }
            System.out.print("\n");
        }
    }

    public static void losangulo(int dimensao){
        char[] losangulo = new char[dimensao];
        int aux = (dimensao + 1) / 2;
        int direita = 0;
        int esquerda = 0;

        Arrays.fill(losangulo, '*'); // função responsável por adicionar o * em cada posição. Obs: Sugestão da IDE

        for (int i = 0; i < dimensao; i++){
            if (i == 0 || i == dimensao - 1){
                for (int j = 0; j < dimensao; j++){
                    if (i == aux){
                        System.out.print(losangulo[j]);
                    }
                    else {
                        System.out.print(" ");
                    }
                }
            }
            if (direita > 0 && esquerda > 0){
                for (int j = 0; j < dimensao; j++){
                    if (j == direita && j == dimensao - esquerda){
                        System.out.print(" ");
                    }
                    else {
                        System.out.print(losangulo[j]);
                    }
                }
            }
            System.out.print("\n");

            direita++;
            esquerda++;
        }
    }
    public static void retangulo(int dimensao, int altura){
        char[] retangulo = new char[dimensao];

        Arrays.fill(retangulo, '*');// função responsável por adicionar o * em cada posição. Obs: Sugestão da IDE

        for (int i = 0; i < altura; i++){
            if (i == 0 || i == altura - 1){
                for (int j = 0; j < dimensao; j++){
                    System.out.print(retangulo[j]);
                }
            }
            else {
                for (int j = 0; j < dimensao; j++){
                    if (j == 0 || j == dimensao - 1){
                        System.out.print(retangulo[j]);
                    }
                    else {
                        System.out.print(" ");
                    }
                }
            }
            System.out.print("\n");
        }
    }
}
